apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-restore-pvc
  namespace: oceanrain
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-cephfs-retain-fs
