apiVersion: batch/v1
kind: Job
metadata:
  name: mariadb-restore
spec:
  template:
    metadata:
      labels:
        app: mariadb-restore
    spec:
      containers:
      - name: backup-ninja
        image: padminisys/backup-ninja
        envFrom:
        - secretRef:
            name: restic-mariadb-env-secrets
        env:
        - name: ACTION
          value: "restore"
        - name: BACKUP_TYPE
          value: "db"            
        - name: RESTIC_HOSTNAME
          value: "oceanrain-mariadb"
        - name: BACKUP_MOUNT_PATH
          value: "/backup"
        - name: RESTORE_MOUNT_PATH
          value: "/"
        volumeMounts:
        - name: backup-volume
          mountPath: /backup
      restartPolicy: Never
      volumes:
      - name: backup-volume
        persistentVolumeClaim:
          claimName: mariadb-restore-pvc
  backoffLimit: 4
