apiVersion: batch/v1
kind: CronJob
metadata:
  name: mariadb-backup
spec:
  schedule: "0 */6 * * *" # Every six hours
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: mariadb-backup
        spec:
          containers:
          - name: backup-ninja
            image: padminisys/backup-ninja
            envFrom:
            - secretRef:
                name: restic-mariadb-env-secrets
            env:
            - name: ACTION
              value: "backup"
            - name: RESTIC_HOSTNAME
              value: "oceanrain-mariadb"
            - name: BACKUP_MOUNT_PATH
              value: "/backup"
            - name: RESTORE_MOUNT_PATH
              value: "/backup"
            volumeMounts:
            - name: backup-volume
              mountPath: /backup
          restartPolicy: Never
          volumes:
          - name: backup-volume
            persistentVolumeClaim:
              claimName: mariadb-backup-pvc
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
